[window]
    opacity = 0.7
    dynamic_title = true

#________1_________2_________3_________4_________5_________6_________7_________812345
[font]
    # normal = { family = "monospace", style = "Regular" }
    # normal = { family = "hack", style = "Regular" }
    normal = { family = "Source Code Pro", style = "Regular" }
    size = 11

[colors.primary]
    background = "#000000"

[colors.vi_mode_cursor]
    cursor = "#DCA561"
    text = "CellBackground"

[mouse]
    hide_when_typing = true

[[keyboard.bindings]]
    action = "ToggleViMode"
    key = "Escape"
    mods = "Shift"
# [[keyboard.bindings]]
# action = "Paste"
# key = "P"
# mods = "Control"
# [[keyboard.bindings]]
# action = "Copy"
# key = "Y"
# mods = "Control"



















#



#


#
