# Preload wallpaper
preload = /home/alex/ya/img/wallpaper/matrix.png

# Set wallpaper
# sh 'hyprctl monitors' 
wallpaper = , /home/alex/ya/img/wallpaper/matrix.png

# Disable splash
splash = false

ipc = on
