;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #CC080808
background-active = #2B3328
primary = #76946A
secondary = #CC76946A
alert = #C34043
disabled = #2B3328

[bar/topbar]
width = 100%
height = 18px
font-0 = "sourcecodepro:size=11;3"
font-1 = "hacknerdfont:size=10;3"
modules-left = xworkspaces
modules-center = date 
modules-right = xkeyboard pulseaudio cpu memory filesystem powermenu
line-size = 2pt
background = ${colors.background}
foreground = ${colors.primary}
radius = 0
border-size = 0pt
border-color = #00000000
padding-left = 30
padding-right = 20
module-margin = 1
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
wm-restack = i3

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-active}
label-active-foreground = ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

[module/date]
; format = "  %Y-%m-%d %a    %H:%M:%S"
type = internal/date
interval = 1
date =  %a %d %b   %H:%M
date-alt =  %a %Y-%m-%d   %H:%M:%S
label = %date%
label-foreground = ${colors.primary}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = "[%layout%]"
label-layout-foreground = ${colors.primary}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = " mute"
label-muted-foreground = #DCA561

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "

format-prefix-foreground = ${colors.primary}
label = %used%

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%{F-} %used%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}



[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 16pt

[settings]
screenchange-reload = true
pseudo-transparency = true

